### ISSUE TITLE
Feature request: refine / narrow down option

### ISSUE THREAD

**Issue by hlplulustg** [farkam135/GoIV#10]
A refine option for narrowing down the possible iv combinations is needed to be independent from any web calculators.

I don't know what the best idea would be to implement this. As of now I simply thought of local storage with past calculations and adding a third button 'refine' under 'cancel' and 'check iv'. When clicking the 'refine' button a dropdown list of past calculations for that specific species appears and the apropriate one can be chosen crosschecking the results after. This method would lay the foundation of another possible feature in the future - an iv database of your pokemon within the app. May be a stupid solution :-D

**Comment by nahojjjen** [comment]
Ive got a version somewhat working logic-wise, but since I have nowhere to put it in the GUI im gonna ask stopyourshenanigains about it.

Here's an image of its current implementation in action: https://cdn.discordapp.com/attachments/211357346910175232/216268156610543617/Screenshot_20160819-205209.png

**Comment by hlplulustg** [comment]
Closing in favor of #153. May be reopened if solution is not satisfying.
