### ISSUE TITLE
Rating Meltan

### ISSUE THREAD

**Issue by Ultraboss77** [farkam135/GoIV#1023]
Edit : seems related to attack as best stat !

**Comment by cdsimpkins** [comment]
I have a regular meltan I can't appraise. 

669 CP
86 hp
Level 24

Mystic
Above average
Attack
Impressed


It doesn't quick appraise either. Returns no results.

**Comment by mokahless** [comment]
Hmm. Do I create a new issue or contribute to this one? Title is rating meltan but description is about lucky meltan.

Since issue is not really described at the start by OP in any useful way, it is more likely to be the same issue not related to lucky.

Dev, I have found a meltan that cannot be properly rated. I have no issues rating it in gamepress's IV calculator.

Attached are screens that will reveal if this is user error (I've checked and rechecked though) and give information that should help find the potential bug in calculations for Meltan.
In this case, without appraising, the list of potentials (see picture) does not include the actual IVs given as per gamepress's IV calculator.

![5](https://user-images.githubusercontent.com/30379366/50246132-63797400-03a2-11e9-8324-4e4407116b3c.png)
![4](https://user-images.githubusercontent.com/30379366/50246133-63797400-03a2-11e9-8317-4d804a2c817b.jpg)
![3](https://user-images.githubusercontent.com/30379366/50246134-63797400-03a2-11e9-9aa7-6634d30dd8af.jpg)
![2](https://user-images.githubusercontent.com/30379366/50246135-63797400-03a2-11e9-9551-ecd6478df7de.jpg)
![1](https://user-images.githubusercontent.com/30379366/50246136-63797400-03a2-11e9-8f9e-83cb11186609.jpg)

Additionally, I have confirmed by manually typing into the calculator that cdsimpkins Meltan cannot be calculated with the current version of GoIV but gamepress's calculator has no issue determining it to be a 53% 13-9-2 IV Meltan. 

I have several other Meltan whose IVs cannot be determined by GoIV. All have attack as their (or one of their) highest stat. This could be coincidence with the small sample size.

**Comment by Ultraboss77** [comment]
Thanks for your analyse, my lucky meltan also has attack at best stat !

**Comment by mokahless** [comment]
I've tested and this issue is fixed as of 5.2.8

**Comment by Ultraboss77** [comment]
Well done !
