### ISSUE TITLE
[Request] Allow decimal percision in IV calculations

### ISSUE THREAD

**Issue by dw13** [farkam135/GoIV#151]
It would be nice to have at least one or two decimal(s) of precision for the individual IV possibilities. It's weird seeing all values rounded to an int, but the average using the original precise values. Eg... Min 98%, Avg 97.78%, Max 98% with only one possible stat in it being 98%.

**Comment by Blaisorblade** [comment]
People have different wishes, but I agree that scenario is bad. Actually the maintainer (@farkam135) wanted to have no decimals, which would avoid this problem.

The reason why the individual possibilities are rounded is that there decimals provide no extra info—a Pokemon can be 94.44444444...% or 97.7777777...%, with nothing in the middle. They might provide some info in the average, though frankly I'm not sure that's very relevant.

Separately, somebody argued GoIV should show the median and not the average, because the average can be swayed by outliers. If that goes through, this problem could also disappear.

Original discussion: https://github.com/farkam135/GoIV/pull/134.

**Comment by rpgrca** [comment]
There are two kind of people using this application, those who really understand what IV is (and are probably techie) and those who just want to know which out of several Pokemon is better to evolve. I would suggest adding a setting with the precision format for all three values. It could start as %02d (printf format), but you could modify it to add any number of decimals you want.

And yes, the median/average one should be another setting, just as the clipboard format one.

**Comment by farkam135** [comment]
Closing, #162 has the final verdict for this as of right now.
