### ISSUE TITLE
Idea for improving CP OCR

### ISSUE THREAD

**Issue by sarav** [farkam135/GoIV#177]
OCR struggles with CP because the background is colorful and keeps changing. But we can use that to our advantage. We just need to 2 (or more?) screenshots and "wipe out" (black, or white) all the pixels that don't match between the two screenshots. Viola! We'd get a much cleaner picture. Especially for pokemon like Abra, etc. More screenshots will just allow wiping out more pixels.

If there's interest in this, I can try to do something like this. Yes, it'll increase the time to show the info dialog, but it'd be a lot more reliable. And we'd probably just need to wait 200ms or so between screenshots.

**Comment by nahojjjen** [comment]
From what Ive seen in the CP scan bitmap images used by the tesseract, the images are already very clean. Since the text is very uniformly colored, the replaceColor method works very well at removing the background. Could you show an image where the suggested ocr improvement would help clean up the image?

**Comment by sarav** [comment]
I think replaceColors cleans it up well enough.
