### ISSUE TITLE
Allow user to manually toggle iv button

### ISSUE THREAD

**Issue by nahojjjen** [farkam135/GoIV#22]
Instead of having the screen analysed all the time to determine if the user is looking at a pokemon, let the user manually toggle the IV button overlay.

Why? Saves battery by not having the screen continuously analysed, and might help users who cant get the auto detection feature to work.

**Comment by hlplulustg** [comment]
Viable options for switching the engine on and off would be button on the notification bar or those bubbles (I forgot the name ...) like here [http://chip01.chipimages.de/crawler/1nHEST6daomJ3YfUDLiciLYWW1plWYl7/com.andcreate.app.pokemon_go_iv_checker/9GiPec3zjcT82HY14ssM0W6aT0SC2eDV](http://chip01.chipimages.de/crawler/1nHEST6daomJ3YfUDLiciLYWW1plWYl7/com.andcreate.app.pokemon_go_iv_checker/9GiPec3zjcT82HY14ssM0W6aT0SC2eDV). Second one would be more comfortable imho.

**Comment by agrajaghh** [comment]
replacing the IV button with a notification action button makes most sense I guess

**Comment by mattaereal** [comment]
I was going to suggest on an issue an enhancement where the user could toggle for automatic IV calculation upon a pokemon description. In order to avoid clicking each time when transferring for example.

**Comment by Blaisorblade** [comment]
> Saves battery by not having the screen continuously analysed

FWIW: Has anybody seen GoIV in the battery profile? I've never.

For the rest, I'd like floating buttons (to hide/show), but all apps that support them have a setting for it, I guess because they're so invasive that so many users hate them.

A notification action button for actually launching the detection, OTOH, would be tricky—you can't take a screenshot right after pressing it because PGo is covered, and it takes lots of actions to press (imagine when you're transferring pokemons and pressing it repeatedly).

**Comment by nahojjjen** [comment]
> FWIW: Has anybody seen GoIV in the battery profile? I've never.

Battery profiler only checks cpu usage as far as I'm aware, and the screen capture runs on the GPU, so you're not gonna see its battery usage. (I could be wrong though)

**Comment by Blaisorblade** [comment]
Hm. Googling leads to http://stackoverflow.com/a/27943583/53974 so I installed https://play.google.com/store/apps/details?id=com.quicinc.trepn, but nothing discusses that specifically. Let's see.

**Comment by agrajaghh** [comment]
> A notification action button for actually launching the detection, OTOH, would be tricky—you can't take a screenshot right after pressing it because PGo is covered, and it takes lots of actions to press (imagine when you're transferring pokemons and pressing it repeatedly).

you could just wait 250ms (or how long it takes for the notification to disappear) and then activate the screen capture

**Comment by Blaisorblade** [comment]
> you could just wait 250ms (or how long it takes for the notification to disappear) and then activate the screen capture

I don't like that because the interval might change with Android skin, system load and what not. The system load alone might make the delay several seconds sometimes, and it'd keep doing that if the phone is slow for a while (because it's warm or what not). I think that would be *very* frustrating.

I'm also not sure that would be better than screenshot mode, but I'd have to try out.

**Comment by hlplulustg** [comment]
> For the rest, I'd like floating buttons (to hide/show), but all apps that support them have a setting for it, I guess because they're so invasive that so many users hate them.

I would prefer floating bubbles. By choosing the position users have better access for IV lookup. (it's easier for me to reach a bubble somewhere on the right side than the IV overlay down on the left. The screen capture only needs to run once tapped and thus save battery.

**Comment by farkam135** [comment]
This will not be implemented right now, might be reopened in the future if we decide to add more modes but for now screenshot/scan screen mode will be the only two.
