### ISSUE TITLE
When I try to predict what level my Pokemon will be above its maximum level for my trainer level, it glitches out

### ISSUE THREAD

**Issue by blahblah3141** [farkam135/GoIV#229]
For example, when I slide my 64% IV Dragonite up to lvl40 as a trainer lvl23, it gives it predicted CP to be 2789, which is clearly too little. It seems to give incorrect values as soon as I go past the lvl24.5 mark, which is the maximum possible value for my trainer level.

It would be nice if this were to be fixed, as even though I am not able to power up my Dragonite (again, for example) past lvl24.5, it is useful to see what CP it can go to for future levels.

**Comment by Blaisorblade** [comment]
> For example, when I slide my 64% IV Dragonite up to lvl40 as a trainer lvl23, it gives it predicted CP to be 2789, which is clearly too little.

I'd assume that's the bug in 3.0.0—there will be a quickfix release (3.0.1) tonight, and the fix to that is already on master.

But then the values are probably wrong even below lvl 24.5, only the error is smaller—can you confirm? It's probably easier to see on lower-level Pokemon.

Technically, 3.0.0 uses, as minimum CP for the average, the current CP, instead of the minimum for that level across all possible IV combinations (the fix is 06dcf68312cfd8dff207d30ede682a283dcc3436).

**Comment by Blaisorblade** [comment]
Closing for now. Please reopen if this reappears with 3.0.1 or later.
