### ISSUE TITLE
Pokémon with accents in their name misidentified

### ISSUE THREAD

**Issue by Remiscan** [farkam135/GoIV#232]
My game is in French. I just tested GoIV on lots of Pokémon, and all of them were correctly identified by the app, except those with an accent in their name. These ones were all identified as Roucool (French for Pidgey), except one who was identified as Roucarnage (French for Pidgeot). I took a few screenshots and tested more Pokémon, and the only thing I noticed that they have in common is an accent in their name.

Here are some screenshots: http://imgur.com/a/6fAH4

**Comment by Blaisorblade** [comment]
3.0.0 has a bug with candy detection and French/Spanish/Italian, which I just fixed in c9521d037c3465f7e31aeaa135acac2050addd0f. So basically it was taking "Bonbons" as pokemon name... Could you see on a couple of examples if that current master 3.0.1 improves anything? (Extra screenshots are not needed).

If not I'll take a closer look.

**Comment by Remiscan** [comment]
It seems to be solved, except for Évoli (Eevee) who is now detected as Abo (Ekans). Thanks :)

**Comment by Blaisorblade** [comment]
Does correction learning work for Évoli? If you correct what's OCRed and rescan the same pokemon, it should pick the corrected name.

**Comment by Remiscan** [comment]
Yes it worked :)

**Comment by Blaisorblade** [comment]
I suspect this is just the OCR misbehaving, reading Évoli as Évo li which is close to Abo. Not much we can do there against our OCR... since correction learning mitigates this, I'm closing as wontfix.
