### ISSUE TITLE
Minor modification in Advanced Information screen

### ISSUE THREAD

**Issue by rpgrca** [farkam135/GoIV#274]
Splitting from #217:

> "Advanced information": If the pokemon has no evolutions (like Snorlax), the "Evolution: Snorlax" combo probably shouldn't be clickable.

**Comment by oskomonzon** [comment]
I don't think anyone will disagree with this one. I'll tackle the issue as soon as I have a moment.
Disabling the selector popup and turning the text black would be the way to go.

Also, it has been discussed to do something similar if the Pokémon has reached his highest evolution, but I'd stay away from that because it is useful in some scenarios when the trainer wants to do some "reverse engineering" on his Pokémon. I think @nahojjjen agrees on this one.
