### ISSUE TITLE
New result layout is slower on many possibilities

### ISSUE THREAD

**Issue by Blaisorblade** [farkam135/GoIV#280]
Now we add widgets for each entry in the table. That's too slow with many possibilities, and slower than before. But note: computing them is totally fine, it's just displaying them that's the problem. Should we truncate that display after 100 possibilities or so?

**Comment by Blaisorblade** [comment]
Note: many possibilities is, for instance, CP 13 HP 10 (which now is enabled again and better stay that way).

**Comment by oskomonzon** [comment]
I just took a look at the implementation there. It's indeed heavy load to add new widgets for each result and too resource heavy for some devices. I think the right way to do it would be to implement a RecyclerView with the proper Adapters.
That widget in particular is ideal for this use case: It's similar to a ListView but as his name implies it "recycles" his childs as they go out of the screen, essencially killing the one that just left the screen in order to create a new one on the other end.

I think that would be the optimal way to do it as it will allow us to show any ammount of results. I know there's not much use to see up to 4096 results on the list but some people seem to care about that.

**Comment by Blaisorblade** [comment]
Excellent point, I keep forgetting about that pattern. Can I assign this to you?

**Comment by oskomonzon** [comment]
Sure, I'll give it a look as soon as I have a moment :+1:

**Comment by rpgrca** [comment]
Header should be "Defense" instead of "Defence", by the way.

**Comment by Blaisorblade** [comment]
That's American vs British English, but @DJCrapsody (who speaks British) agreed we can stick to American.

**Comment by rpgrca** [comment]
I don't really mind, we study British American down here, but both the Appraisal narrowing and the result list header should be the same.

**Comment by oskomonzon** [comment]
I'm issuing a PR with the reworked implementation. Attached the same strings to allow localization and avoid inconsistencies.

**Comment by DJCrapsody** [comment]
Defense instead of Defence is good. Apparently Defense is American English but Defence is other English including British English. I'll run through the strings and make sure its in American English.
