### ISSUE TITLE
`scanPokemon` might hang the application

### ISSUE THREAD

**Issue by Blaisorblade** [farkam135/GoIV#284]
This is a regression introduced (I think) in https://github.com/farkam135/GoIV/commit/9ac1355ba784d1b85700d110edfd775c8421c377 from #262.

@sarav's #248 changed the code, but we have still Pokefly sending an intent to itself, and flags not getting changed if that doesn't happen.

I'm not 100% sure there's a bug, but if there is no bug it's by luck, not by design. And luck isn't reliable. We should refactor this.

- To fix this bug, we could send again an empty intent when the OCR isn't initialized.

   But the new logic uses default values (which I find worse), so an empty intent is not something we're handling.

  Moreover, those default values end up in the dialog instead of having something *actually* missing there.

- Alternatively, now that @sarav's fixed the root cause for the OCR being not initialized, we could drop that code for ocr == null. Recent releases have shown that handling problematic conditions badly is more painful than crashing—crashing resets the app to a working state, hiding the problem makes it harder to reset the app, with users claiming they need to reboot their phone (though I still don't believe that's necessary).

**Comment by sarav** [comment]
Agree with letting the app crash for stuff that shouldn't be happening if the code is right. Only expected nulls should be checked against (say, if OCR scan can return a null if it couldn't find a string, etc).

**Comment by sarav** [comment]
One unintended way to reproduce this issue (this doesn't happen when you use it with the game as intended):

* Start GoIV in normal mode, but don't start the game
* Find some old screenshot of the game you took on you phone (not someone else's)
* Open it in some fullscreen picture viewer
* GoIV will think it's the game screen and the IV button will show up
* Click it -- it might hang and not do anything.
* If it doesn't hang, click "cancel" in the input dialog
* You'll go back to the picture viewer and the IV button will show up again.
* Click it again and it'll definitely hang at this point.

This **COULD** be and issue unrelated to this (that we don't care to fix) because GoIV might be getting confused with the Navigation buttons going away in full screen viewer mode and maybe the input dialog box drawing goes wrong. For my device the IV button actually shows up over the navigation button on the screenshot (not the real navigation button) -- so there's that. But the fact that it's hanging silently might still give us a hit to where it's misbehaving and fix the original issue. And since it's easy to reproduce, it should be easy to debug too.

**Comment by Blaisorblade** [comment]
You're right about navigation, but that should produce a failed scan not a crash. Evidence: I looked at the screenshot from takeScreenshot in the debugger. Also, some users might have tried this. Finally, we should ensure snapshot mode accounts for this. And in fact, it seems GoIV mostly manages to scan the info... I'm confused.

The crash still seems about `infoShownSent` stuck to `true`, as always. Since this variable was created to prevent duplicated intent delivery, I think we should drop it. Or find the code path where it is not cleared to confirm what the bug is.

Re size: when we get full screen mode, the captured screenshot uses the wrong displayMetrics—the vertical height is small because it assumes the bars above and below are shown, but in fact the screenshot itself includes the above bar, so the part below of the screenshot is cut.

> For my device the IV button actually shows up over the navigation button on the screenshot (not the real navigation button) -- so there's that.

Same here, I assume it's an effect of the same issue.
