### ISSUE TITLE
Trainer level doesn't always update properly

### ISSUE THREAD

**Issue by imapokemon4** [farkam135/GoIV#309]
Steps to reproduce:
  
1. Install [vysor.io](http://vysor.io/) (I'm not sure if this is necessary, but it's what I use while testing my device)
2. Change to a release build variant in android studio
3. Run app from android studio
4. Force stop GoIV
5. Clear all GoIV data
6. Run GoIV
7. Use vysor to type <insert your level here> into trainer level
8. Click start
9. Try to check IVs for a pokemon and see that you can't line up the red dot
10. Check notification to see that it still reads trainer level 1
  
In order to get it to update to my trainer level I had to go back into GoIV and click stop.
  
Then click my trainer level until the keypad thing pops up and click the green checkmark.
  
Sometimes it doesn't pop up, so I just keep clicking until I see that the visible trainer levels around mine change to the correct ones (e.g. from 22, 2, 3 to 21, 22, 23).

**Comment by sarav** [comment]
I have no clue what this use case is, but yes, if you change the trainer level, you have to stop and start the service. This is the expected behavior for the current code. 

We could change it though. But it's a bit of work.

**Comment by imapokemon4** [comment]
That's not the problem

**Comment by imapokemon4** [comment]
I type 22 and click start

**Comment by imapokemon4** [comment]
PokemonGo opens but my trainer level is still level 1

**Comment by imapokemon4** [comment]
In order to get it to update to my trainer level I had to go back into GoIV and click stop.

Then click my trainer level until the keypad thing pops up and click the green checkmark.

Sometimes it doesn't pop up, so I just keep clicking until I see that the visible trainer levels around mine change to the correct ones (e.g. from 22, 2, 3 to 21, 22, 23).

**Comment by Blaisorblade** [comment]
You say:

> I type 22 for my trainer level and click start.

What you need to do:
- type 22 for my trainer level
- click the green checkmark
- click start

It's sure annoying as hell. But since it affects half of my apps, I believe it's Android's fault—that's how the widget works IIUC. We might still be able to do sth. about it—and maybe in fact all these apps misuse the widget. But I delegate an answer to people with more Android expertise.

**Comment by imapokemon4** [comment]
Can we use a different widget? Or just friggin text box and a button?

**Comment by Blaisorblade** [comment]
@oskomonzon, ideas?

**Comment by oskomonzon** [comment]
It's a little late here, so I'll give it a look tomorrow. I think we'll need to track the place where we save and load the trainerLevel and where does the Start picks it from.
If for some odd reason the numberpicker is failing to update the value I guess we can make it store the setting onChange and let the start button take it from the sharedPrefs.

I'm curious about if this happened too with the old implementation (EditView IIRC). Anyway, shouldn't be too hard to track down and fix.

I must confess that if it's not easily fixable (I hope that's not the case) it would be among the last of my priorities as the case use is pretty unusual :P

**Comment by Blaisorblade** [comment]
@oskomonzon There are two problematic behaviors, but you seem to misunderstand which is in question:
- you can't change the trainerLevel while the service is running. That's what you seem to be addressing, but that's not what this issue is about, and that's tricky to fix because the trainerLevel is copied in many places—and this isn't due at all to the GUI code.
- after you type in the control, you must press the checkmark or your edit is ignored. That's an usability bug, I think in Android, and the subject of this issue. Can we avoid it?

**Comment by Blaisorblade** [comment]
Here's what you see after you return to the app, if you type your level and start before pressing the green checkmark (which on my phone is not easy but possible):

![image](https://cloud.githubusercontent.com/assets/289960/18127221/465bc846-6f7f-11e6-8c21-168f64b34705.png)

**Comment by Blaisorblade** [comment]
Issue fixed by #319.

Apparently @imapokemon4's PR in his fork closed this issue here—I'll ask GitHub what's going on, since that seems a bug. (To be clear: @imapokemon4 you've obviously done nothing wrong 😉).
