### ISSUE TITLE
Have default IV screen show evolved stats when possible at the current level

### ISSUE THREAD

**Issue by skaforey** [farkam135/GoIV#332]
I guess I'm probably in the minority here, but I kind of liked the way one of the older versions worked where we would see the CP if were to evolve at the current pokemon level.

I was thinking of making this an option, but trying to think of the best way this would be implemented.

For mons that do not get evolved (or are at their highest evolution already), I think it makes more sense to  default to show what the CP would be at the max level.

However, for mons that can be evolved, I would prefer to show the CP of the mon at the current level for the next step in the evolution chain.

Do other people have opinions on how to make this nicely configurable?

**Comment by oskomonzon** [comment]
This has been discussed before and we know it's a thing that will keep coming up from time to time because there are two strong divergent use cases spread around the userbase:

- Those who aim to check how powerful will be each Pokémon at it's max allowed by the current trainer level.
- Those who simply want to see how will the Pokémon be affected by evolving it without further resource investment.

Knowing this and taking that into account we decided to hold a design philosophy that prioritize usability. Since our implementation makes use of a seekbar, our tests lead us to the realization that it's much easier to slide the "thumb" from the seekbar all the way to the left to hit the current Pokémon level than starting at that point and trying to adjust it with precision to the max allowed by trainer level (usually somewhere in the middle). This is specially true when we are dealing with low level Pokémons where the amount of "steps" in the seekbar increases considerably.

The reason why there is no setting related to this is that, again, our design philosophy is to keep the amount of settings at the minimum while trying to cater to a wide range of users. It's not an easy task.

We are always open to discussion and all the feedback is welcome. Thanks for your concern.

I'm summoning @nahojjjen, @DJCrapsody and anyone else in the development team in case they have something to add to the discussion.

**Comment by rpgrca** [comment]
Much of the discussion can be found in #223.

**Comment by DJCrapsody** [comment]
Did a few research on Reddit and GitHub.
There have been 3 users that requested to see evolved stats at the current Pokemon level.

Based on easy-to-use feature perspective, as explained by @Blaisorblade in #233:
> Here's my rationale when I proposed this as an easy default: we wanted it to be easy to get both "current level (here 20)" and "max level you can reach now (here 28.5)". To get to the current level, you just go all the way to the left which is easy(-ish). If we default to 20, to get to 28.5 you'd have to go all the way to... the center? That's not harder to pick. >

IMO, to have a better balanced UX (easy-to-use while relevant), we can change it to display it at current level. It will require changes to some other elements.

Remove the progress of the SeekBar, we are not a music playing app, we are using it just to change values: http://stackoverflow.com/questions/28567494/android-how-to-hide-seekbar-progress

Adding a 'step value' to determine the max based on trainer level: http://stackoverflow.com/questions/7329166/changing-step-values-in-seekbar

I can take this up if the above proposed changes looks ok.
@Blaisorblade @nahojjjen @rpgrca @oskomonzon @skaforey
