### ISSUE TITLE
Remember appraisal narrowing based on name

### ISSUE THREAD

**Issue by rpgrca** [farkam135/GoIV#335]
Throwing an idea: Right now custom pokemon names are associated to pokemon races assuming names are unique. I wonder if it could be possible to also remember the appraisal narrowing based on that custom name.

A possible workflow (A):
1. I have a Hitmonlee, rename him as "Goku".
2. I appraise it, it gives me HP.
3. I calculate IV, it guesses the pokemon type incorrectly, I correct it to Hitmonlee, I also check HP narrowing.
4. Just as it associates Goku with Hitmonlee, it could associate HP to him as well.

Most of the cases are the way around: renaming after calculating IV (B):
1. I have a Hitmonlee, appraise it, gives me HP.
2. I calculate IV, it gives me 88%.
3. I rename Hitmonlee as Hitmonlee.88.
4. Eventually I appraise him again (after powering up, for comparison, etc). Go to workflow (A), step 2.

This is tied with having an option to purge all the associations, and/or backup/restore them (for example, useful when switching phones, or if you play with a tablet at home and phone outside).

**Comment by Blaisorblade** [comment]
The current assumptions is that the same name isn't reused for different species, and that's often barely true (some remove the species from the name altogether). We're in fact planning to drop this assumption and use just the candy name + cost.

But I can totally have two Eevee87 if they have the same average IV percentage, so that assumption you propose works even less often. So I'm closing this in favor of #354, where the user has more explicit control.

**Comment by ergoithz** [comment]
This could be reopened as now we also have weight, size and sex to identify a pokemon.
