### ISSUE TITLE
Allow sorting the list of possibilities

### ISSUE THREAD

**Issue by leppie** [farkam135/GoIV#341]
Some times is it hard to look for possible values due to sorting. Seems it is always sorted by HP ascending.

![image](https://cloud.githubusercontent.com/assets/127666/18177916/76d5e6e8-707c-11e6-8bb8-492cdc9f3adc.png)

I want to make a suggestion that clicking on any column, will toggle sorting on that column, click twice for reverse order. 

Also the default sorting should be based on appraisal hints given, iow, if DEF, then DEF should be the sorted column. (Let me know if the latter should be an additional issue)

**Comment by oskomonzon** [comment]
Sorting ivScanResult's ivCombinations should be more or less easy hacking together a custom Comparator class.

About sorting by appraisal hints... I'm not sure how would be the best way to handle it since the user is able to pick multiple stats for evaluation. I guess we could sort it in the order they are displayed but I'm not sure if it will be the best solution.

**Comment by leppie** [comment]
@oskomonzon When multiple stats are selected you only need to sort on one of them, they will always be equal.

**Comment by oskomonzon** [comment]
Lol, you are right, @leppie.

**Comment by leppie** [comment]
@oskomonzon  Dont worry, I asked myself the same question :D

**Comment by rpgrca** [comment]
After thinking some more about this, I think dynamic sorting isn't completely necessary. Those are all hypothetical values, with only one correct, so you are probably interested only in the minimum and maximum values (aka, highlighting them so that you can notice them at a glance, or sort by IV).

However, I still think tables should be sorted from left to right, and that clicking on headers should sort them. At the very least, sort by IV which is what the majority will care about.

**Comment by amcameron** [comment]
@rpgrca : but since GoIV doesn't eliminate all possible combinations specified by the appraisal feedback, being able to sort by different columns could more easily narrow the range of rows you have to search to establish the minimum and maximum values. For instance, if you know Attack is 13 or 14, sorting by attack would make all such rows adjacent to one another, rather than having to skip over rows in between because the default sort is on Stamina.

**Comment by nahojjjen** [comment]
@amcameron As far as i know, we're going to add the rest of the appraisal input after the refactor is done, so changing something to make it easier for the user to manually think about the appraisal answer wont be needed.

**Comment by Blaisorblade** [comment]
Agreed with @nahojjjen. IMHO, both sorting left-to-right (for aesthetics) and sorting by IVs (for functionality) still make some sense.

**Comment by leppie** [comment]
Does c1dfddf really address this, or just sort them 'better'?

**Comment by Blaisorblade** [comment]
It just sorts them better. But now we have working appraisals, so users don't need to search for pokemons matching appraisal results by hand—and this seemed to be the opinion of most here. Do you think that's not enough?

**Comment by leppie** [comment]
In most cases yes, but if you get say 100 possibilities, having the option to sort, can refine it your own classification. Is making sorting really that hard? (I would not think so, unless it is a control/UI thing)

**Comment by nahojjjen** [comment]
I dont actually think its possible to get 100+ results unless you're checking some 10 cp level 1 pokemon. I dont see a reasonable usecase.

**Comment by Blaisorblade** [comment]
> In most cases yes, but if you get say 100 possibilities, having the option to sort, can refine it your own classification

Again: now that we have appraisals, what's the use case? I've reopened the issue for now, but I also doubt there's a point.

**Comment by Blaisorblade** [comment]
Closing again for lack of further justifications.
