### ISSUE TITLE
"CP354" recognized as "CP3 54"

### ISSUE THREAD

**Issue by rpgrca** [farkam135/GoIV#358]
(Virtually) Latest code is misreading Nidoran CP354 as "CP3 54", so it always shows as 10 in the GoIV screen.

![screenshot from 2016-09-03 19-11-14](https://cloud.githubusercontent.com/assets/15602473/18227878/654b8074-720a-11e6-8a0b-89bf5ac676aa.png)

Not sure how a white space managed to get there, since it isn't in the tesseract's white list...

**Comment by Blaisorblade** [comment]
Tesseract does that constantly. The code for HP handles this better I think by filtering non-digits (rather than cutting away two characters).
I've been afraid to reuse it because, well, these are always heuristics and you're never sure it'll be an improvement. Specifically, "ZP 354" would become "2354".

**Comment by sarav** [comment]
I think we should throw out all spaced from all the OCR text and then do any comparisons. Including pokemon name, candy name, etc. We can remove the spaces in a similar way when we create the pokemap so that the look up continues to work. That should remove a lot of errors IMO. Including this one.

**Comment by nahojjjen** [comment]
@sarav i agree that no ocr should actually need spaces, except for maybe candy recognition, where the space might be helpful in determining where the "candy" portion begins.

**Comment by Blaisorblade** [comment]
But right now Candy is often split into two words. IIRC this is fixed because "Pikachu Can" is still closest to Pikachu.

I've thought of hardcoding the word for "Candy" in the languages we support, though I'm wary of that (right now GoIV works for unsupported languages). Maybe that's the way to go?

Or we could just keep "Candy" in there and hope that the closest thing to "PikachuCandy" is "Pikachu"—but maybe "MewCandy" seems as close to "Dewgong" as to "Mew" (distance = 5), so this isn't necessarily robust.

Maybe we should just log centrally all scanned strings (from users or at least from us) and try new heuristics on those.

**Comment by sarav** [comment]
Having a unique list of user OCR results would be super helpful! Can crashalytics help there?

But we might get a lot of junk because of renames.

I'm tempted to say we break languages we don't support or add a setting to get number of characters in Candy name. Then we can just chop off that many characters. Any idea on the user stats on locales? Wonder how they'd even use it if the text is all in English anyway.

**Comment by rpgrca** [comment]
Another for the backlog: Pidgey, CP300. This one is tricky, if the brightness is high, it gets correctly detected, but if it is not as bright, it gets detected as CPS00.

![screenshot from 2016-09-24 00-42-05](https://cloud.githubusercontent.com/assets/15602473/18805878/eca2d820-81ef-11e6-8430-d391243bfbb0.png)

**Comment by Blaisorblade** [comment]
As long as S always means 3 we can add a fix, but does it? Another PR adds a replacement mapping S to 5, which frankly looks much more plausible.

https://github.com/farkam135/GoIV/pull/431/files#diff-a486e6cbd07638779e0b6f9af368f3b7R244

BTW, with brightness you talk about the background from the pokemon right? I assume the screen brightness setting does not influence the actual pixels we read.

**Comment by rpgrca** [comment]
Yes, the bloom effect that in pidgey is quite noticeable. I'd have thought the OCR would fail when bloom was at its maximum (and the numbers are barely noticeable), but it actually fails when it's at its lowest.

**Comment by sarav** [comment]
5 in HP gets recognized as an S. There are reports of it in reddit too. So, if we add anything, it should S -> 5.

**Comment by rpgrca** [comment]
An Ivysaur CP800 is recognized as "CPSOO" (soo). My guess is that the leaves . I agree that S → 5, but it would be nice if GoIV remembered the correction so that the next time it shows the correction instead (which would work with the original "CP3 54", but would probably fail with CP800, CP500, CP300, etc). Can't always win.

**Comment by Blaisorblade** [comment]
> but it would be nice if GoIV remembered the correction so that the next time it shows the correction instead

Good point, we should generalize the caching code.

> By the way, while the cursos appears on CP blinking, you must click on it to get the keyboard to show. Maybe it should display the keyboard directly? After all, you can't calculate anything unless you input the number.

👍 , but I'll leave that to our GUI guys @oskomonzon @nahojjjen @DJCrapsody . You might want to file a new issue and tag them so it's not lost here.

**Comment by nahojjjen** [comment]
Since the current CP scanning logic removes any non-numerical characters, this issue should no longer occur. I have not gotten any reports about it lately either, so closing the issue.
