### ISSUE TITLE
Ease seeing appraisal while inputting it

### ISSUE THREAD

**Issue by Blaisorblade** [farkam135/GoIV#373]
Following up from @rpgrca in https://github.com/farkam135/GoIV/issues/327#issuecomment-244755425:

>> I'm afraid it might be a bit too much to ask for someone to remember three or more piece of information regarding appraisal.

>> Maybe it would be better if GoIV also stayed on top of the appraisal information, slightly above so that the user can read and add the information as the trainer is mentioning it. Or just two independent screens altogether, one that pops up when the appraisal information is being read so that you can complete it, with the other being the usual one with the appraisal information incorporated.

@nahojjjen adds:

> I agree with the memory problem, Ive been using the appraisal version for a day now & it was annoying. I'll see if i can find some easy way to "move up" the entire info dialog when the appraisal box is expanded so the user can click appraise without closing the dialog. Pokefly is pretty messy though so I might not be able to

**Comment by oskomonzon** [comment]
IMHO this should be taken into account while we refactor Pokefly and implement the solution after that. It may be messy to achieve with the current implementation.

**Comment by Blaisorblade** [comment]
@oskomonzon Can you elaborate? Do you refer to @nahojjjen's plan or to @rpgrca's?

**Comment by rpgrca** [comment]
Been using the latest code with the extra appraisals. It's usable, I had to redo a few times because I had forgotten the correct appraisal. I noticed a couple of things, so I give some feedback based on those:

1. Only way to retain all the information is to remember just one word out of each appraisal. In my case, as Team Valor, I remember "like", "decent", "proud" and "amazes" for the percent phrase, and "greatness", "job", "excellent" and "WOW" for the range. So, my suggestion would be to highlight each of the words (or similar, but just one for each phrase) so that the final user can create the same association. I'm unsure whether having the whole phrase (as it's now) can be that useful, a combo with just one word (maybe even letting the user choose which word he will remember for each appraisal) could be much faster.
2. The first thing I complete are the checkboxes because they don't require extra clicks. Was thinking that maybe it should be at the top instead of the middle of both appraisals.

**Comment by leppie** [comment]
I would prefer it if just remembered, then you can close GoIV, run appraisal again and fix/add missing info.

**Comment by oskomonzon** [comment]
@Blaisorblade I was talking about @nahojjjen's idea of moving up the inputs layout. But this morning I took a better look at the code and it's entirely possible:

![screenshot_2016-09-06-10-01-33](https://cloud.githubusercontent.com/assets/10285769/18274577/6b5e55f2-7419-11e6-9b65-f492cea61e72.png)

**Comment by Eccenux** [comment]
Maybe use swipe up/down gestures to move the window to top/bottom? IIRC you only need to change gravity and apply layout changes.

This would also help when trying to change input value with non-standard keyboard (e.g. Swype is obstructing view).

**Comment by oskomonzon** [comment]
@Eccenux the softkeyboard issue should be handled by android:windowSoftInputMode. I'm hoping we get it right after refactoring, once the code is a little cleaner.

In my current testing branch I'm just moving the window to the top (because we need a lot of space to manouver the in-game menu) when the refine by appraisal panel is expanded and back to the bottom on collapse. But it was just for testing purposes.

I think after refactoring it would be better to leave that layout as his own new window as opposed to a collapsible, that way we would get rid of the CP, HP, and Arc adjustments part in order to allow for a cleaner screen in small devices and not risk covering the "Appraisal" option from PoGo menu.

**Comment by Blaisorblade** [comment]
Is the soft keyboard issue #345?
Also: separate this layout on its own window is the *first* step of this refactoring, and nobody actually got started on this.

**Comment by Eccenux** [comment]
Changing windowSoftInputMode for the activity doesn't help. Probably because the layout is not full height window... But that's a bit different thing... (old issue, so I'm guessing, not #345)

Anyway I just think using swipe to move the window would be nice UX. This would be similar to moving similar Ingress widget.

**Comment by Blaisorblade** [comment]
> Anyway I just think using swipe to move the window would be nice UX. This would be similar to moving similar Ingress widget.

Would be cool, now we just need somebody with a clue how to do that. But it can be amazingly little code, just an `OnTouchListener` handling `ACTION_MOVE`:
http://android-er.blogspot.de/2014/01/implement-drag-and-drop-movable.html

**Comment by Eccenux** [comment]
Swipe is not feasible after all. Even if you somehow manage to catch touch events user will probably click on something while trying to do the gesture... But moving window on click of appraisal group should be fine.
