### ISSUE TITLE
Use nidoran gender recognition also when nidoran's detected from the candy

### ISSUE THREAD

**Issue by Blaisorblade** [farkam135/GoIV#381]
We only use gender recognition `if (pokemonName.toLowerCase().contains("nidora")` (see `OCRHelper`), but that fails for renamed pokemons.

But apparently also candies can be misgendered:
https://github.com/farkam135/GoIV/pull/308#issuecomment-244835226

We "just" need to move Nidoran gender recognition at a different point, without duplicating code or doing it twice. `PokemonNameCorrector` doesn't have access to the image (and probably shouldn't) so is not an option. It might be enough to *move* Nidoran gender recognition to the code OCRing candy.

Ideas?

**Comment by sarav** [comment]
Sometime ago, I noticed one of the gender characters was OCRed as Q. So, I went and check the male and female again. The problem is that Nidoran♀ always gets identified as NidoranQ and Nidoran♂ always gets identified as Nidorand. Both NodiranQ and Nidorand are seen as closer (or just as close?) to Nodiran♀.

I think a simpler fix than the color checking would be:
1. Just let OCR do it's thing
2. Then run through the similarity check to see if it's any Nidoran.
3. If it is Nidoran, then go back to original OCR output and see if the last letter is a Q or a d and pick the corresponding gender character.

This would be a simple string correction function fixNido(String OCRtext, String cleanPokeName) and returns a fixed up Nidoran name. And this can be called from candy or pokemon name scanning functions.

Actually, I'm not even sure if we should look at the pokemon name anymore after the evolution candy count based detection is done. But that's a separate discussion.

**Comment by sarav** [comment]
Went ahead and implemented it myself. Tested it. It works.

On an unrelated node, how does OCR even work for ja locale? The characters are not latin characters and we seem to initialize tesseract with a whitelist of latin characters only (except the gender chars). I'm guessing GoIV doesn't work well for them? And hopefully user corrections is helping them a bit?

**Comment by DJCrapsody** [comment]
I don't think its properly supported for the jap client. there aren't enough or any demand for it since the start.
