### ISSUE TITLE
Pick colors for IV highlighting

### ISSUE THREAD

**Issue by Blaisorblade** [farkam135/GoIV#388]
In #336 we implemented better IV highlighting—which colors to use was still an open discussion. We should figure that out.

**Comment by Blaisorblade** [comment]
Pinging @Remiscan since he already did a few experiments.

**Comment by Remiscan** [comment]
Here's what I tested and the reasoning behind it:

- Light Green / Dark Green : http://i.imgur.com/b1rgsOE.png

I tested this one because I felt that 13-14 and 15 should both be in different shades of green, because they both represent good IVs. I thought the contrast between the light green text and the background was a bit low, so I tried making the light green darker.

- Green / Dark Green : http://i.imgur.com/2MrQO4k.png

But then the two shades of green were too similar, so I tried using blue instead, since the spectrum of light goes red-yellow-green-blue, it felt like it could work.

- Green / Turquoise : http://i.imgur.com/XSG56kJ.png

I still wanted 13-14 and 15 to look close to each other, because the difference in IV is really small, so I picked turquoise instead of blue, because it's closer to green.

- Green / Blue : http://i.imgur.com/HUvqkHl.png

Then i just tried with blue, because it makes it easier to differentiate 13-14 and 15, and I thought people might prefer that.

- Dark Green / Blue : http://i.imgur.com/qT99AJZ.png

And I tried the original dark green with blue again.

I think I would be ok with any of them, except the green / dark green one. I'd vote for turquoise but that's just because I like the color :p 

I guess it depends on whether we want the colors to show the "closeness" between 13-14 and 15, or to just be easy to distinguish. I think the "easy to distinguish" ones (the green / blue ones) would probably be better, if people feel that blue is a natural progression of the red-yellow-green spectrum.

**Comment by Blaisorblade** [comment]
> I think the "easy to distinguish" ones (the green / blue ones) would probably be better, if people feel that blue is a natural progression of the red-yellow-green spectrum.

Personally, I find easy to distinguish most important, especially accounting for sunlight and non-perfect screens (or less extreme variants).

**Comment by Paxtez** [comment]
For the each stat IV, why not use a gradient like the catch color circle?  0 pure red, 15 pure green, with 7/8 being yellow?  Simple, matches the theme used by the game.

**Comment by Blaisorblade** [comment]
I think we already decided to follow the appraisal system and there are good arguments there—many care about the difference between 14 and 15.

The catch color uses red-orange-yellow-green, so it does have enough colors. But yellow on white background is unreadable.

**Comment by sarav** [comment]
@Blaisorblade Wait, are the catch colors based on IV too? Just asking for curiosity's sake. 

@Remiscan I actually like the light green/dark green one and it seems perfectly readable on my desktop. But I don't know how it'll look on the device. Not a huge fan of blue/turquoise though. I think geen/dark green also conveys the fact that they are pretty close. So, maybe that's what we should pick?

Or maybe change the background color? All white isn't really that nice when you are playing the game at night. It kinda blinds you anyway.

**Comment by Blaisorblade** [comment]
On the actual colors I'm not sure. I suspect I'd prefer dark green/blue. Probably using the same blue as the team picker for consistency, `Color.rgb(61, 159, 255)`, also because we use the same yellow. Those colors have decent contrast on white background.

> @Blaisorblade Wait, are the catch colors based on IV too? Just asking for curiosity's sake.

No, they're based on how hard the catch is—see e.g. https://pokemongo.gamepress.gg/catch-mechanics.

**Comment by Blaisorblade** [comment]
Deferring to not block the release.
- We don't have consensus and it's hard to pick.
- Even if I picked anything, I couldn't apply the choice without knowing the codes for the colors used in the screenshots.

**Comment by Remiscan** [comment]
Here are the colors I used in my screenshots:
red: #8A0808;
yellow: #DBA901;
dark green: #088A08;
blue: #069CC8;
light green: #99CC00;
green: #2BBE10;
turquoise: #06C8AF;

I also tried to take the dark green/blue combination and make the colors a bit brighter: http://i.imgur.com/jenqZv5.png
red: #B10000;
yellow: #F1A900;
green: #00A000;
blue: #0099EF;

I also tried to use the colors from the team picker (I made the yellow more orange to have better contrast), but the previous ones have a better contrast on white and grey backgrounds: http://i.imgur.com/UGSnLVw.png
red: #EE5B5B;
orange: #FFA826;
green: #08CA26;
blue: #3D9FFF;

I don't know what else to try, and it probably wouldn't be very useful to have lots of variations of green and blue to choose from. All I know is I'd prefer darkgreen/blue to the current colors.

**Comment by nahojjjen** [comment]
Closing this unless discussion sparks up again.
