### ISSUE TITLE
Document EVERYWHERE the need for extra taps

### ISSUE THREAD

**Issue by Blaisorblade** [farkam135/GoIV#452]
Document in
- Changelog
- FAQ
- anywhere appropriate

that 
"If the IV button doesn't show up in a Pokemon screen, try to tap the screen once to see if it shows up".

Thanks to @sarav for reminding me in #451.

**Comment by DJCrapsody** [comment]
how about... Just a toast when user clicks on start?

**Comment by sarav** [comment]
Toasts disappear too soon IMHO when trying to read for the first time. And they feel like their linger on for too long once you know the text.

We could add it to the instructions in the Main UI.

**Comment by sarav** [comment]
Note: Tap the screen once if the IV button does or doesn't show up when you expect it to. 

Something like that. Toast is okay too if others prefer that. No strong opinion.

**Comment by sarav** [comment]
P.S: I didn't want to nitpick on the changelog, but if we are going to educate the users, might as well be accurate.

I changed that para in the changelog (spelling mistakes and some clarification).

The screen scanning logic will now only activate after you touch the screen. So instead of scanning every 750 milliseconds, it will only scan a couple of times with a short delay when you touch the screen. If you tap it too fast, it'll wait for you to be done tapping before scanning. So, gym fights should cause zero scanning.

**Comment by Blaisorblade** [comment]
> P.S: I didn't want to nitpick on the changelog

To some extent, allowing that is why I'm updating `CHANGELOG.md` before the release.

**Comment by Blaisorblade** [comment]
We ended up not changing any code but just docs, also because the translations are frozen. Let's hope that's enough. Closing.
