### ISSUE TITLE
Share Intent does nothing when PokeFly is stopped

### ISSUE THREAD

**Issue by DJCrapsody** [farkam135/GoIV#464]
Suggestion
1. Inform user that pokefly needs to be started. 
2. Fire an intentservice when using share intent?

Pulled from #463.

**Comment by sarav** [comment]
(2) IntentService is a completely unrelated thing to this. We should not use that in GoIV with the current requirements.

The main reason is due to the lack of trainerLevel, etc when the service isn't running. Or when even the activity hasn't been started. Keep in mind that the Share option will also show up. So, (1) is the reslly only option. We should do it as a toast.

**Comment by DJCrapsody** [comment]
(1) isn't exactly the only solution... Another solution is something we have been talking about, an always on IV button. But we'll lose the share intent (which we all know have this bad behaviour), which also loses share via Now on Tap functionality.

**Comment by Blaisorblade** [comment]
> The main reason is due to the lack of trainerLevel, etc when the service isn't running. Or when even the activity hasn't been started.

That could arguably be setup without starting a service (if we refactor things), see #499.

**Comment by sarav** [comment]
I'm still worried that allowing sharing while the service isn't started is going to result in false reports of "it's not working" bugs because people forgot to update the trainer level. Forcing a service start/stop kinda avoids that,

**Comment by NightMadness** [comment]
I think we should tell user if he needs to active service. Also we should process/respond even if screenshot option is disabled.

Options:
1. Tell user to select level and start service
2. Process image Tell user to make sure level is set correctly
3. Process image and add trainer level to dialog gui (this will fix the long task of switching level 4 to 5 clicks/swipes but we dont have much space in dialog screen) 

3 is most complex but I think the best solution

**Comment by thearaks** [comment]
I think @NightMadness 3 steps can be easily implemented in ShareHandlerActivity.
It could also be styled as a "floating" Activity with transparent background or scrim.

**Comment by Blaisorblade** [comment]
FTR, here's a request to fix this on Reddit:
https://www.reddit.com/r/GoIV/comments/54s6oo/suggestion_launch_using_on_tapassistant_function/

**Comment by Blaisorblade** [comment]
BTW, we already get false bug reports because of having the wrong level, I've forgot to update it myself; the only difference is that right now you can check the level in a notification.

Or to put it another way: there's a (slight) usability problem with selecting the right trainer level after the proposed change, but also with the current UX. On the other hand, the input dialog is already cramped, especially on small phones.

Ideas:
- the dialog could have an extra field when invoked for a screenshot
- when detecting something's wrong (no possibilities), we could also remind the user to check the level (even though it won't detect all mismatches)

**Comment by thearaks** [comment]
@Blaisorblade A possible solution for the false bug reports:
While detecting, if we can't find the Pokémon level, we could try increasing the trainer level (+1) and restart detection; if it doesn't fail stick with the new trainer level.

**Comment by Blaisorblade** [comment]
As mentioned, we don't really notice (yet) if we fail detecting the level. When I notice it fails, it's often because the pokemon animation hides the arc in part. So having the level increased automatically (without confirmation) sounds questionable.

OTOH, proposing this to the user (and allowing confirmation with one tap) avoids this problem. Then you just need to merge #499 and (IMHO) turn the ScreenInfo into a non-singleton (or something like that), so that you can more easily have a separate instance for the increased level while you're just trying it out. (Other designs are possible but this seems a rather clean one).

**Comment by sarav** [comment]
The problem with changing the level at run time is that the arcpoints are calculated and cached once during the start of Pokefly. A bunch of other things also need to be initialized before we can do the scan. So, if we support scanning without starting Pokefly, then it we'd have to do all the initialization and destroys for every image. Seems quite a bit expensive.

Yet another option is when an image is shared, we could just go ahead and start the service in screenshot mode, let the user know (in a toast) and process the image.

**Comment by Blaisorblade** [comment]
> So, if we support scanning without starting Pokefly, then it we'd have to do all the initialization and destroys for every image. Seems quite a bit expensive.

Based on #499, I don't think the arcpoints so expensive relative to compressing/saving/scanning an image (which takes seconds). The biggest cost seem at most 80 FP computations of points (with trig. functions, OK).

Or do you refer to initializing the GUI? That's probably a much bigger concern...

> Yet another option is when an image is shared, we could just go ahead and start the service in screenshot mode, let the user know (in a toast) and process the image.

I'd also be fine with that.

**Comment by BraisGabin** [comment]
> Yet another option is when an image is shared, we could just go ahead and start the service in screenshot mode, let the user know (in a toast) and process the image.

Other option is move the main code outside the service and create two differente services: the actual service and an `IntentService`. Both implementations call the same code.

**Comment by sarav** [comment]
@BraisGabin there'd be absolutely no point in having two services running. 

@Blaisorblade I meant the all the init stuff. Including the UI, etc. Ton of work to start and stop the service. I  can implement the last recommendation I gave. In a week or two.

**Comment by jordan2936** [comment]
What ppl love yall
