### ISSUE TITLE
Unknown crash due to view being null

### ISSUE THREAD

**Issue by DJCrapsody** [farkam135/GoIV#477]
Not sure what is causing the crash. Could not reproduce, but seems like many are facing this.

> Fatal Exception: java.lang.RuntimeException: Unable to stop service com.kamron.pogoiv.Pokefly@6616382: java.lang.IllegalArgumentException: view must not be null
>        at android.app.ActivityThread.handleStopService(ActivityThread.java:3101)
>        at android.app.ActivityThread.-wrap21(ActivityThread.java)
>        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1448)
>        at android.os.Handler.dispatchMessage(Handler.java:104)
>        at android.os.Looper.loop(Looper.java:148)
>        at android.app.ActivityThread.main(ActivityThread.java:5460)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
> Caused by java.lang.IllegalArgumentException: view must not be null
>        at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:346)
>        at android.view.WindowManagerImpl.removeView(WindowManagerImpl.java:111)
>        at com.kamron.pogoiv.Pokefly.unwatchScreen(Pokefly.java:448)
>        at com.kamron.pogoiv.Pokefly.onDestroy(Pokefly.java:497)
>        at android.app.ActivityThread.handleStopService(ActivityThread.java:3082)
>        at android.app.ActivityThread.-wrap21(ActivityThread.java)
>        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1448)
>        at android.os.Handler.dispatchMessage(Handler.java:104)
>        at android.os.Looper.loop(Looper.java:148)
>        at android.app.ActivityThread.main(ActivityThread.java:5460)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by sarav** [comment]
Seems to be due to something in the unwatchScreen(). 
If we can reproduce this issue, try adding these line (they look like pointless lines from an example code I saw, so I dropped, but maybe it matters) right after touchView is created:

LayoutParams dummy)arams = new LayoutParams(1, LayoutParams.MATCH_PARENT);
touchView.setLayoutParams(dummyParams);

**Comment by DJCrapsody** [comment]
None of my devices are facing issues (and that makes it hard for troubleshooting) :(

**Comment by Blaisorblade** [comment]
That crash is due to `touchView` being `null` unexpectedly, so @sarav's lines shouldn't be relevant.

Anyway, this can be triggered because START_STICKY's fault. If the service is killed and restarted, `onStartService` is called with a null Intent and does nothing, and `onDestroy` will find `touchView` being `null` unexpectedly.
http://stackoverflow.com/a/3963376/53974

@DJCrapsody can you link to the initial reports for context, as a rule? Your report doesn't say what the users do to get this.

A vaguely related crash is http://crashes.to/s/ddc9bf5a0e0, where `screenScanHandler` is `null` inside the `onTouch` handler for `touchView`. As if... `onTouch` was called after `onDestroy`? `START_STICKY` doesn't explain that—how is onTouch still active after onDestroy? `onStartService` called with `null` sets up no `onTouch`.

**Comment by DJCrapsody** [comment]
@Blaisorblade no one reported the crash, this was pulled from fabric

**Comment by Blaisorblade** [comment]
> @DJCrapsody can you link to the initial reports for context, as a rule? Your report doesn't say what the users do to get this.

In this case, one source of the report is http://crashes.to/s/021ee0fb2a9. No user reports, but at least there are statistics (happens across OSs).

**Comment by sarav** [comment]
@Blaisorblade How do you know that the null was actually due to touchView being null and not, say, it's layout being null. I have no idea what removeView does internally.

But I agree that what you said is the most likely case. I'll look into it and try to fix it over this week. Do you have any pointers on how kill and restart is handled for a service? I'm surprised to hear that onCreate is not called if it's killed and restarted but onDestroy is always called.

**Comment by DJCrapsody** [comment]
onCreate **should** be called if the service is killed and restarted.

http://stackoverflow.com/questions/10670839/if-android-restarts-a-service-is-oncreate-called-again

**Comment by sarav** [comment]
Then I'm not sure how onStartCommand could be called with a null intent. There'd be no way to get trainer data if that happens. And then onDestroy is getting called somehow? That seems like a questionable design -- especially considering that an Intent is fully self contained.

I'll look into this more.

**Comment by Blaisorblade** [comment]
> @Blaisorblade How do you know that the null was actually due to touchView being null and not, say, it's layout being null.

Because the message says "java.lang.IllegalArgumentException: view must not be null". I opened `android.view.WindowManagerGlobal` (from API version 24) and the message appears accurate.

Regarding the layout being null: `addView(view, params)` seems to set the `layoutParams` of `view` to `params`, at least in `ViewGroup.addView`, but that's much less conclusive.

> Then I'm not sure how onStartCommand could be called with a null intent.

The [docs for START_STICKY](https://developer.android.com/reference/android/app/Service.html#START_STICKY) are not ambiguous: "if there are not any pending start commands to be delivered to the service, it [onStartCommand] will be called with a null intent object, so you must take care to check for this." See below for better motivation.

In the scenario I described, the lifecycle should be (apparently) `onCreate`, `onStartCommand(non-null intent)`, `onDestroy`, `onCreate`, `onStartCommand(null intent)`, `onDestroy`. If such a scenario happens, it will certainly cause a crash given the current code; and the docs we found suggest this scenario is allowed.

The reason the intent is null later is that with `START_STICKY` the intent is not preserved—there's a separate `START_REDELIVER_INTENT` for that, and that's probably what we want.

Docs below make sense to me—the point of `START_STICKY` is that if the service is restarted, it should do nothing till it gets a new intent giving it a new job. I do suspect we want `START_REDELIVER_INTENT` because Pokefly "does a job that should be immediately resumed".

Quoting from https://developer.android.com/guide/components/services.html

> START_NOT_STICKY
If the system kills the service after onStartCommand() returns, do not recreate the service, unless there are pending intents to deliver. This is the safest option to avoid running your service when not necessary and when your application can simply restart any unfinished jobs.

> START_STICKY
If the system kills the service after onStartCommand() returns, recreate the service and call onStartCommand(), but do not redeliver the last intent. Instead, the system calls onStartCommand() with a null intent, unless there were pending intents to start the service, in which case, those intents are delivered. This is suitable for media players (or similar services) that are not executing commands, but running indefinitely and waiting for a job.

> START_REDELIVER_INTENT
If the system kills the service after onStartCommand() returns, recreate the service and call onStartCommand() with the last intent that was delivered to the service. Any pending intents are delivered in turn. This is suitable for services that are actively performing a job that should be immediately resumed, such as downloading a file.

**Comment by Blaisorblade** [comment]
> Because the message says "java.lang.IllegalArgumentException: view must not be null". I opened android.view.WindowManagerGlobal (from API version 24) and the message appears accurate.

Precisely, all sources of that exception have form:
```java
        if (view == null) {
            throw new IllegalArgumentException("view must not be null");
        }
```

**Comment by sarav** [comment]
@Blaisorblade makes perfect sense. We should change it to START_REDELIVER_INTENT.
