### ISSUE TITLE
You HAVE to select team. 3 options only. Where is "No team"

### ISSUE THREAD

**Issue by MrWhacco** [farkam135/GoIV#500]
When starting the app, GoIV Offline, latest version. You only have 3 options in the team's dropdown. 
I however have not joined a team yet (lvl 20), i know this only affects the appraisal from the team leader. wich in turn makes it harder to calculate the exact IV for the Pokémon.

Anyway.. Please add the option to select "No team", And if selected the appraisal selection ingame is disabled.. I think this should be an option. Even if GoIV cant calculate the exact IV for Pokémon X. 

Thx

**Comment by Blaisorblade** [comment]
Oh I see, good point. But until next release, how bad is it to select the "wrong" team in the dropdown? The only downside is that you'll still be able to use appraisals and it won't make sense.

**Comment by nahojjjen** [comment]
What's the goal of a change adding "no team"? If the only goal is to remove the appraisal line in the input dialog then I'd rate this issue as very low priority / wontfix.

**Comment by MrWhacco** [comment]
This is not rly an issue, its just a request. ofc i can compile it with a "no-team" option myself and disable the appraisal input when selected. However, No Team is still a "team".

**Comment by Blaisorblade** [comment]
For me, the question is "what's the real problem". And if the only problem is only that you're lying to a computer, I agree this is low priority. A slightly more important problem is if a user thinks they have to pick a team.

Still, this seems rather low priority.

> ofc i can compile it with a "no-team" option myself and disable the appraisal input when selected. 

If you can do the changes and you think they could be merged, feel free to submit a PR ;-).

> However, No Team is still a "team".

Not 100% sure what you mean there—is this about how "No Team" is represented internally?

**Comment by nahojjjen** [comment]
Dont misunderstand MrWhacco, I fully support that you bring the issue to our attention. Thanks to that, we can have a discussion on whether it should be implemented or not based on the benefits and costs of time and code complexity added.

I suppose one "fix" would be to add a team "no team" and add blank strings or error strings to match the currently existing teams. This would create a "bad" scenario where the appraisal window is still available but weird-looking to people who choose "no team", but it would have the benefit of not adding separate logic in the code for this situation, which would mean the code would not become (~aprox) more complicated.

The other fix would be to add "no team", and then have a show/hide method on the appraisal text. I don't like this fix as it would add new code-paths and cases to consider in the code. Also it would make Pokefly more complicated, which sucks..


Another thing to consider is where the "no team" option would be in the drop-down menu in the main screen. Intuitively, the "no team" would be the first result. However, the current listing is in order of popularity, so mystic is the most probable "good default". We'd also have to handle new logic for the drop-down if we change the order of the items so that users from old versions have their team settings correctly transferred, despite the old numbering index being out of sync. 
Considering that, the "no team" option would have to be added last in the drop-down menu, if it was added.

**Comment by ThomasMldr** [comment]
May I ask why you would want to pick no team? Can you even appraise Pokémon as a lone wolf?

**Comment by Blaisorblade** [comment]
Closing as long as this question stays unanswered:
> For me, the question is "what's the real problem".

Feel free to discuss here, if you have a compelling argument to make for reopening.

**Comment by NightMadness** [comment]
I think the idea is to add option to pick no team (team harmony?) and hide apprisal refining expension button/title.
No need to disable button, we can just hide it when we build the scren, I didnt check the code paths, but I assume we only need to hide it when we first display the confirmation dialog.

You can calculate IV with no appraisal.

For the reason:
It probably feels uncomfotable for the user to need to pick a team in order to use GoIV when the user explicitly doesn't want to pick any team.
