### ISSUE TITLE
Avoid taking over the clipboard

### ISSUE THREAD

**Issue by oskomonzon** [farkam135/GoIV#511]
I may be wrong here, but I've been testing the new clipboard features by @nahojjjen (wich are amazing by the way) and I feel it would be better to trigger the "Clipboard" function manually instead of having it running automatically every time we calculate the IVs.

The rationale behind this is that most of the time I'm not willing to rename a Pokémon if the results are not interesting enough, and having it taking over my clipboard all the time may be a little too invasive if I'm doing multitasking of some sort.

I'd rather have a little more control about when to override the contents of my clipboard, maybe by clicking on the results?

It may also display a toast for visual feedback: Clipboard set to "⑪⑫⑬Vaporeon"

**Comment by Blaisorblade** [comment]
I guess that problem is orthogonal to @nahojjjen's feature, except that the clipboard function now is much more useful. The feature can (and could) be disabled altogether, but you'd like finer control right?

I can't really multitask with PoGo, but I guess your big phone has big RAM 😉 , so it can make sense. But I personally wouldn't like extra clicks, so I'd like an extra option for your mode. \<cue in discussion on option bloat>

**Comment by oskomonzon** [comment]
I'm used to copy and paste text between apps, so I find bothersome anything that just overrides my clipboard without my consent (and visual feedback), so I would be willing to trade finer control for an extra tap since most of the Pokémon that I scan are not interesting enough to rename (meaning just one extra tap once in a while). But that may be just me and I'm fine with that.

I say no to option bloat xD

**Comment by nahojjjen** [comment]
@oskomonzon just to make sure, you're aware that clipboard on/off has been in settings since 2.x, and that even before my clipboard change the app inserted information to the clipboard?

I suggest solving the issue by adding a clipboard icon which when pressed adds the info to clipboard even if the setting is off.

**Comment by oskomonzon** [comment]
@nahojjjen I'm aware, I bring it up now because with your changes it became so much useful and after being testing it for a while I came up with this scenario.
A clipboard button somewhere would be nice, indeed. If we can avoid cluttering.

**Comment by nahojjjen** [comment]
I closed this issue and opened #532
