### ISSUE TITLE
CP now starts often with 3 when it shouldn't

### ISSUE THREAD

**Issue by Blaisorblade** [farkam135/GoIV#513]
After adding 9d3e716766b44a74ff5eed97d1449bd0ce5551c6, now the OCR of CP often starts with 3 when it didn't before. I suspect I might have to revert that, and then also d9855fdf29218c34bee0094c6688691b16eb50bb and the associated simplifications in #502 :-|.
That can be done after merging that PR though (in fact, it's easier then).

**Comment by nahojjjen** [comment]
I wrote / have modified the cp scan part of the code which was originally not removing numbers,(so what you modified in 9d3e716766b44a74ff5eed97d1449bd0ce5551c6 ) I intentionally had it always remove the two first characters instead of non-numbers because the "cp" text is read as several different things on several different backgrounds/screen sizes, and occasionally what it reads contains a number, but it's quite consistent in that whatever it reads, is's two characters. (cp, cP, Cp, c3, s3, 73, 53 etc are combinations i think ive seen.)

For the record, we cant split the scan area to crop out "cp" before it's OCR'd because it moves depending on how many numbers are in the cp value.

**Comment by Blaisorblade** [comment]
Thanks, I'll revert that, and add your explanation as a comment to prevent somebody "fixing" it again like this. (This is also what tests are for).

**Comment by nahojjjen** [comment]
Yea sorry, I should probably originally have documented it after my testing.

**Comment by BraisGabin** [comment]
At the beggining I was using replaces and substrings too. I finally decide to proccess the CP this way: https://github.com/BraisGabin/pokescreenshot/blob/master/processing/src/main/java/com/braisgabin/pokescreenshot/processing/Tess.java#L60-L74

The CP number is centered and the CP label is not, so I use that property. The first recognition tell you where is `CP509`. Then you remove the "CP" part from the recognition area.

Some times `CP` is `CID`, and similar things...

**Comment by nahojjjen** [comment]
Your suggestion of cropping away "cp" sounds neat, but until that is implemented I suggest we revert to the substring(2) method as it was in most cases accurate.

**Comment by nahojjjen** [comment]
#521 should revert the change.

**Comment by nahojjjen** [comment]
#521 has been merged
