### ISSUE TITLE
Cannot update to 3.3.1

### ISSUE THREAD

**Issue by WizardStan** [farkam135/GoIV#575]
Attempting to update to 3.3.1 from 3.2.0 and below fails, including update within app and downloading package from github. It was necessary to uninstall the previous package and install entirely from scratch.
Secondary issue that may mask the problem is that 3.3.0 appears to have a different signature from all other versions for some reason, so "updating" from 3.3.0 to 3.3.1 is actually a new install which leaves both versions active.

**Comment by nahojjjen** [comment]
This is a known issue, but thanks for the report.

We changed the package name because of a misstake in 3.3.0, but it was reverted in 3.3.1. This means that any attempts at updating from/to 3.3.0 will fail. Updates from below 3.3.0 to anything above 3.3.0 might also behave strangely.

Unfortunately this is nothing that can be fixed on the already released versions, and 3.3.1 is already modified to not have this issue in the future.
