### ISSUE TITLE
App causes overheating

### ISSUE THREAD

**Issue by vmwinckler** [farkam135/GoIV#577]
I checked this from the first version I downloaded. The app is causing the phone to overheat when used continuously with the game open.

**Comment by sarav** [comment]
What version are you testing? We've done a lot to reduce the amount of screenshots we take (which is the most intensive part of GoIV). 3.3 certainly shouldn't have any overheating issue. Heck, I even run GoIV all the time between playing PoGo so that I don't have to kill/restart PoGo due to black screen issues.

**Comment by nahojjjen** [comment]
Im afraid this is probably caused by two things:

1. Pokemon go takes a shitton of cpu&gpu time
2. The screen recording api GoIV uses can be resource intensive on some phones.

I recommend you run goiv in screenshot mode if normal mode does not work for you, as it puts a lot less stress on the gpu.

**Comment by vmwinckler** [comment]
I'm using the latest version of the app. Complicated having this problem on a Galaxy S7 Edge, processor and memory are no problems.

**Comment by nahojjjen** [comment]
I have a Samsung S7, no edge. The app does not cause overheating on my device.

If you have a more measurable issue or more specific what's happening please tell me. I'm afraid this is not something I can work to fix, as I dont know where to begin. 

It's possible that this issue is limited to your specific device :/

**Comment by vmwinckler** [comment]
I really do not know how to better detail the situation. I simply can not keep the app active along with the game, after a few minutes the device begins to overheat. It really can be a specific problem with the S7 edge, this device has a high power consumption.

**Comment by nahojjjen** [comment]
Could you check your phones processor, gpu  and ram usage?

You can enable checks for those in your phones developer settings.

**Comment by vmwinckler** [comment]
I dont active developer settings anymore because PoGo stops works when ativate (not more root only). Strange but true. :(

**Comment by sarav** [comment]
@vmwinckler Where did you install the app from?

**Comment by vmwinckler** [comment]
@sarav 
Game - Play Store
GoIV - APK from GitHub with only activate "install from other sources" (not need Dev settings)

**Comment by sarav** [comment]
Hmmm... yeah, seems like a one off case.

**Comment by nahojjjen** [comment]
If pokemon go stops working when you activate developer settings without running GoIV then there's something wrong with your phone.

**Comment by vmwinckler** [comment]
@nahojjjen I bought this S7 a week before the Game launch, just to play. I always kept the developer mode active, but the 3 (or 4) past updates the game stopped working, opened but did not care, then deactivated the developer mode and logged in normally.

**Comment by nahojjjen** [comment]
I havent turned off developer mode since I got it, I always have the setting which shows my touches active. Ive also run cpu/gpu checking several times with GoIV.
