### ISSUE TITLE
Minor UI improvements for Appraisal Refining

### ISSUE THREAD

**Issue by crd** [farkam135/GoIV#591]
* Don't ask the user to choose an overall phrase / mark checkboxes / choose a stats phrase if it's not necessary to disambiguate appraisal values
* Consider preselecting an overall phrase or stats phrase for the user. I never bother calculating IVs for pokemon that aren't 82.2% -- if "Choose overall phrase" was defaulted to the top-tier selection that would save me clicks
* Default Appraisal Refining menu open, rather than closed. Every time I calculate IVs it's necessary to first click "Appraisal Refining". This might require additional UI optimization: Perhaps make overall and stats phrase selections something other than dropdowns to save space

**Comment by nahojjjen** [comment]
This issue is difficult to tackle as it's actually 3 separate points, but I'll try to address them:

1. We dont know if the appraisal information is needed until the refining calculation has been performed. We could perform the iv calculation when the appraisal window is expanded, and refine the possibilities on the fly, but that'd cause problems such as "what should happen if the user changes the cp/hp of the pokemon with the appraisal window open" and "how should we deal with if the user changes what they selected in the appraisal window". I personally dont want this to be implemented as it would complicate the code, and if something like #600 gets implemented well, it could become a non-issue for many.

2. Adding a setting for automatically selecting >80% if appraisal is expanded could make sense.

3. Adding a setting for this could also make sense, however we'd need to define how we'd like  to make it work in combination with #600 if it gets implemented.

**Comment by nahojjjen** [comment]
Closing this as its not a well defined issue, but rather a collection of potential issues that would require separate discussion.
