### ISSUE TITLE
GoIV overlay cuts off when keyboard is activated?

### ISSUE THREAD

**Issue by nahojjjen** [farkam135/GoIV#63]
http://imgur.com/a/jw7hx

https://www.reddit.com/r/GoIV/comments/4y7bgi/200_released/d6lwc0w?context=3

**Comment by Antonio-Kuri** [comment]
#61 Are you guys on that? I was setting up to it, but had some problems

**Comment by farkam135** [comment]
This is actually so that the user can see what they are typing.

**Comment by Antonio-Kuri** [comment]
It covers the whole thing on kit-kat. Still let you to change stuff but you can't see anything

**Comment by rpgrca** [comment]
This wouldn't be that bad if the cursor was set to the end of the number, but instead it's placed at the beginning, so you have to guess the position while editing. If the cursor was placed at the end instead, you would delete the number with backspace. Maybe you could just delete the whole number when tapped? It would be much faster inputting the correct number instead of editing the old one.

**Comment by mattaereal** [comment]
I was thinking on a quick fix like you said, deleting entirely the number. Having to manually edit or deleting it seems too much trouble.
