### ISSUE TITLE
GOIV no buttons on LG G6

### ISSUE THREAD

**Issue by Kantana28** [farkam135/GoIV#677]
Hi Devs, any chance of fixing GoIV to work on the LG G6?  This phone has a 18:9 ratio screen with resolution of 1440x2880.  I have tried using the built in LG app scalar to drive PoGo at 16:9, 16.7:9 and finally 18:9 ratios but none of them allow the GoIV to appear.  I also tried using the battery saver for games to drive PoGo at lower resolutions but no joy.
I also tried the AZ screen recording app and that works so likely cause is the unusual screen ratio.  The action button bar is on screen at all 3 screen ratios so that isn't what is causing the button to not appear.

**Comment by Kantana28** [comment]
Just a new observation if both GoIV and PoGo are forced into 18:9 screen ratios using the LG app scalar then the GoIV button will appear however none of the scanned information is correct:

Name is wrong
HP is blank
Candy is blank
IV arc is wrongly aligned

If these are manually entered then GoIV will show correct values.
Can we get this fixed in next release?

**Comment by nahojjjen** [comment]
Sorry for not replying, I missed this thread. I wrote a comment in a similar issue thread #679

**Comment by Kantana28** [comment]
Any chance to get this working on LG G6?  I just tried the updated S8 version but stil no joy.  Let me know if you need to collect any info.

**Comment by nahojjjen** [comment]
Damn, I was hoping the s8 patch would work on the G6 since the screens are similar. Do you have a dev environment setup so you can test changing things and testing them on your G6? I think one issue could be that the S8 fix isnt getting applied to the G6, although I dont know if that fix would be precise enough. I dont know how the G6 works with the android screen api either, nor do I know how the compatibility mode the G6 has warps PoGo...

**Comment by Kantana28** [comment]
I can turn on the dev options on my phone but beyond that not much else.
The G6 rights now only shows the GoIV button if both GoIV and PoGo are both set to full screen eg 2880x1440 which is a 2:1 ratio.  I'll attach 2 screenshots here one showing GoIV button and one of the scanning on the device.

![capture _2017-05-08-19-45-24](https://cloud.githubusercontent.com/assets/26335643/25802943/4228f722-3427-11e7-9051-67ffc83a074f.png)
![capture _2017-05-08-19-45-40](https://cloud.githubusercontent.com/assets/26335643/25802942/4228491c-3427-11e7-97fc-c9f8b23c5fa3.png)

**Comment by TripSixes** [comment]
Looks like the vertical height is not calculated properly.. I would bet
that the scanning of the arc is detecting that level because the arc is
either wider or narrower than what GoIV is expecting and that point is
simply the last point that GoIV has overlap of it's own expected arc and
the actual game arc.  I think this is also backed by the CP scanning
correctly, but not the lower screen info (due to shifting of each capture
region the further down they are).

**Comment by Kantana28** [comment]
Sounds like you have a bead on it, let me know if you need beta testing, thanks.

**Comment by lilfire** [comment]
Loved the "quick IV preview" feature on my previous phone, and got really sad when i got my G6 and found out that its not working on my new phone. are the any estimated date for a fix?  I would be happy to test any beta version if you guys need testers.

**Comment by nahojjjen** [comment]
No eta, but we're aiming for next release, or if that fails, the release after that.

**Comment by nahojjjen** [comment]
This issue should be solved with the scan recalibrate feature released in 4.0.0

If the issue persists, please open a new issue.
