### ISSUE TITLE
Show level in GoIV button

### ISSUE THREAD

**Issue by JoseLSegura** [farkam135/GoIV#863]
It will be nice to show the Pokémon level in the quick assesment button, with the IV%

**Comment by nahojjjen** [comment]
There are many things that would be useful to see in the quick assessment button, depending on the scenario. Some of the things that have been requested are:

The pokemon dex#
The scanned CP
The CP will be when its max evolved and level 30

I agree that your suggestion is most likely more useful in most scenarios than the abovementioned, but the current goal with the quick-button is to give iv info as fast as possible, and adding any type of additional information would marginally decrease the speed at which the iv can be interpreted.

If the user wants to see the level because he doesnt know if goiv scanned it right, then we should improve the level-scan instead. If the user wants to know the level of the pokemon before throwing it away, I think it's currently good enough to see the level-arc or press the iv button.

If you have more arguments for adding lvl to the iv-preview, please just add another comment.
