### ISSUE TITLE
Can't get auto-update to work on Android

### ISSUE THREAD

**Issue by dominicbarnes** [farkam135/GoIV#870]
The app properly detects new versions on start-up and when I manually check for updates, but when I try to update the app it seems to run in the background but never do anything. I presume it's hitting an error and just not reporting it, but it's hard to say.

What kind of steps can I follow to debug this issue? (not an Android developer, but I do work in software)

**Comment by thearaks** [comment]
Hi @dominicbarnes, thanks for your report!
This is a known issue on Android 7.1+ due to how package install permissions are changed.
The latest GoIV release include a fix for this and, starting from the next update, the update install process should work flawlessly.
Please let us know if you are not running Android 7.1+ or if the problem will persist even with the next update!
