### ISSUE TITLE
Errors scanning Alolan Exeggutor with v5.0.7

### ISSUE THREAD

**Issue by gradha** [farkam135/GoIV#927]
After upgrading to v5.0.7 I was able to scan a few alolan Exeggutors but found one which doesn't return a valid value, so I've stopped prunning them in case their IVs were miscalculated. Other pokemon scan fine. Possibly a dupe of #925. See attached screenshot.

![alolan error](https://user-images.githubusercontent.com/101927/40874699-e3d7799e-6672-11e8-8a0c-bdc979b62eb9.jpg)

**Comment by udnp** [comment]
Hi GoIV pj. tema.

Spanish pokemon type dragon is "DRAGÓN".
https://github.com/farkam135/GoIV/blob/master/app/src/main/res/values-es/pokemons.xml#L18

So I think that this issue occurs because GoIV OCR character whitlist now dose not have "Ó" and other acute accent characters.
https://github.com/farkam135/GoIV/blob/master/app/src/main/java/com/kamron/pogoiv/pokeflycomponents/ocrhelper/OcrHelper.java#L83

**Comment by nahojjjen** [comment]
The screenshots you show hasn't identified the alolan form, its just listed as "exeggutor". If it's identified as alolan, it should say "alolan exeggutor".

**Comment by gradha** [comment]
Unfortunately the dialog doesn't let me override the detected form, only non alolan versions are available.

**Comment by udnp** [comment]
I checked my debug log for this issue on Spanish android system, 
and result was following:

https://github.com/farkam135/GoIV/blob/da993e485c3be21a1fd19bd8b323c6803aef7820/app/src/main/java/com/kamron/pogoiv/scanlogic/PokemonNameCorrector.java#L160-L161

  [1] `scanData.getPokemonType().toLowerCase()` returns `planta / dragon`
  [2] `pokeInfoCalculator.getTypeName(14).toLowerCase()` returns `dragón`

Therefore, string of [2] is not contained string of [1], so Alolan Exeggutor dose not selected.

**Comment by udnp** [comment]
Then I added `Óó` in the OCR whitelist characters above.
But its OCR result [1] contained `dragon`, not `dragón` that I need.

I've still not found the reason why OCR result does not get `dragón`.

**Comment by thearaks** [comment]
Hi @udnp 
I think the problem is that Tesseract is using a model trained on the english language.
That's why it ignores accented letters even if whitelisted.
The easier solution is to replace the `ó` with a plain `o` (and all the other accents as well) in the type names strings when PokeInfoCalculator loads them from resources! ;)

**Comment by nahojjjen** [comment]
#933 I tried to make a quick solution based on what thearaks suggested. @udnp does it work for you?

**Comment by udnp** [comment]
@thearaks thanks for your advice.

I've confirmed that my test works well in the case where eng.traineddata is replaced with spa.traineddata from https://github.com/tesseract-ocr/tessdata/blob/3.04.00/spa.traineddata

**Comment by udnp** [comment]
@nahojjjen thanks for your work.

I've confirmed that it works well for Alolan Exeggutor and Eevees evolutions on Spanish language Android system.

**Comment by mewio** [comment]
5.0.7 is failing to recognize Alolans as Alolan on my all-English system, too.

**Comment by udnp** [comment]
@mewio, Could you try to do calibration again from notification area like following?
![calibration](https://user-images.githubusercontent.com/17121615/40099001-0ff592ac-5919-11e8-8905-ed8014ea4dc4.png)

**Comment by mewio** [comment]
I have recalibrated, twice. It didn't help either time.

**Comment by gradha** [comment]
Alolan form is detected now, thanks.

**Comment by mewio** [comment]
5.0.8 recognizes one of my Alolan Exeggutor, but it reports the other two as regular Exeggutor.
